Add sync transaction support
Restream/reindexer-py pull request #17
Opened 2024-12-02 08:53 UTC by AlexAUtkin

- Add sync transaction support
- Rework QueryResultsWrapper
- Clear and simplify code

2024-12-05 13:43 UTC, MadSchemas requested changes

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/__init__.py
> -# from pyreindexer.index_definition import IndexDefinition
Кажется, можно удалить?

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/include/queryresults_wrapper.h
> +			it_ = qres_.begin();
Эта логика не совсем правильная. В общем случае по QueryResults можно гарантированно проитерироваться 1 раз. Если это клиентские QueryResults, то сервер их закроет на своей стороне, как только выдаст все данные, и если QueryResults не были выданы за один Fetch, то корректный begin() получить уже не выйдет (и клиент, и сервер эти данные уже удалят)

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		delete transaction;
А не будет ли здесь лучше завернуть TransactionWrapper в unique_ptr и отдавать его в Py_BuildValue через вызов release(), чтобы вручную не делать delete в случае ошибок?

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	char* json = const_cast<char*>(wrSer.c_str());
А что именно здесь даёт const_cast? FromJSON в любом случае принимает string_view (пусть даже в Unsafe-режиме он сделает const_cast внутри себя)

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		item.SetPrecepts(itemPrecepts);
Вот тут при переходе на v4 можно будет сделать move. Предлагаю пока todo оставить

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	assert((StopTransactionMode::Commit == stopMode) || (StopTransactionMode::Rollback == stopMode));
А что такое stopMode? Почему-то не могу нигде определение найти

2024-12-05 13:43 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	assert((StopTransactionMode::Commit == stopMode) || (StopTransactionMode::Rollback == stopMode));
И тут вот тоже

2024-12-05 17:17 UTC, AlexAUtkin commented on pyreindexer/__init__.py
> -# from pyreindexer.index_definition import IndexDefinition
Нет. Красная строка означает, что она была удалена. Я не могу удалить удаленное

2024-12-05 17:20 UTC, AlexAUtkin commented on pyreindexer/lib/include/queryresults_wrapper.h
> +			it_ = qres_.begin();
Оно мне так досталось. В комментарии эта особенность указана.
_When the results are fetched the iterator closes and frees a memory of results buffer of Reindexer_
Если это однажды измениться, то это будет правильный код. А сейчас абсолютно без разницы

2024-12-05 17:27 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		delete transaction;
Да, так будет лучше. И оно уже сделано, но в другом бранче: [add_query_support](https://github.com/Restream/reindexer-py/blob/feature/add_query_support/pyreindexer/lib/src/rawpyreindexer.cc#L503). Там все такие места переделаны. А здесь было для единообразия используемых подходов. В рамках этого PR переделка не планируется.

2024-12-05 17:40 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	char* json = const_cast<char*>(wrSer.c_str());
Затрудняюсь ответить, это копипаста.
Убрал, но в другой ветке (это упростит мне слияние)

2024-12-05 17:40 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		item.SetPrecepts(itemPrecepts);
Оставил, но в другой ветке (это упростит мне слияние)

2024-12-05 17:42 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	assert((StopTransactionMode::Commit == stopMode) || (StopTransactionMode::Rollback == stopMode));
Вот что значит не собирать в Debug. Осталось от процесса разработки

2024-12-05 17:42 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	assert((StopTransactionMode::Commit == stopMode) || (StopTransactionMode::Rollback == stopMode));
Убрал

2024-12-05 17:48 UTC, AlexAUtkin commented on pyreindexer/lib/include/queryresults_wrapper.h
> +			it_ = qres_.begin();
Убрал

2024-12-06 11:05 UTC, MadSchemas commented on pyreindexer/__init__.py
> -# from pyreindexer.index_definition import IndexDefinition
Тёмные темы не щадят дальтоников - был убеждён, что оно зелёным выделено)

2024-12-06 13:50 UTC, MadSchemas approved these changes

2024-12-06 13:51 UTC, merged