Add Query support
Restream/reindexer-py pull request #18
Opened 2024-12-04 12:08 UTC by AlexAUtkin

- Add Query class
- Rework Exceptions
- Change README.md file generator: now pydoc_markdown
- The minimum supported version of Reindexer is set to 3.30

2024-12-06 13:50 UTC, MadSchemas requested changes

2024-12-06 13:50 UTC, MadSchemas commented on .github/workflows/deploy-workflow.yml
> +          attestations: false
А что именно даёт этот флаг?

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/query.py
> +    def op_and(self) -> Query:
А почему именно такой нейминг выбран вместо обычных `and()`/`or()`/`not()`?

Как будто в вызывающем коде они чуть симпатичнеебыли бы: `where("id", CondType.CondGe, 2).or().where("id", CondType.CondLt, 7)`

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/query.py
> +    def where_uuid(self, index: str, condition: CondType, *keys: str) -> Query:
Вообще у питона в стандартной библиотеке есть тип uuid.UUID. Может здесь их принимать вместо абстрактных строк?

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/query.py
> +             keys: Union[simple_types, tuple[list[simple_types], ...]] = None) -> Query:
Здесь keys это скорее forced_sort_values (и в комменте бы тоже исправить, а то сейчас там "If values argument specified, then items equal to values..." при том, что аргумента 'values' нет вообще)

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/reindexerinterface.h
> +	Error err_{errOK};
У Error свой дефолтный конструктор есть, нет смысла errOK явно передавать

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/reindexerinterface.cc
> +	return execute([this, query, &result] {
А почему query стал по значению передаваться? Там всё же string

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/reindexerinterface.cc
> +	const int QRESULTS_FLAGS = kResultsJson | kResultsWithRank | kResultsWithJoined;
Лучше полнотекстовый ранг запрашивать, только если пользователь его требует (у Query флажок IsWithRank() есть), в остальных случаях серверу будет дешевле его не отправлять и не добавлять в json. Обычно ранг нужен для отладки, а вот в проде не так часто.

Для транзакций вообще нет смысла его запрашивать (но для них он перформанс не аффектит)

UPD: Перепроверил - для транзакций, оказывается, сервер тоже будет ранг слать рядом с айтемами, если ему передать kResultsWithJoined, но там всегда будут нули

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	err = item.Unsafe().FromJSON(wrSer.c_str(), 0, mode == ModeDelete);
`wrSer.c_str()` -> `wrSer.Slice()` (там во-первых, сам `FromJSON` принимает string_view, а во-вторых, для WrSerializer вызов `Slice()` чуть дешевле, чем вызов `c_str()`)

В МРе по транзакциям уже не стал об этом писать - проще здесь поправить

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	err = item.Unsafe().FromJSON(wrSer.c_str(), 0, mode == ModeDelete);
И тут `wrSer.Slice()`

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<reindexer::Variant> keys;
Я бы здесь и в других подобных местах предложил VariantArray вместо `std::vector<reindexer::Variant>` - чуток сэкономим на аллокациях, да и по конексту этот тип подходит

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<std::string> keys;
Тут бы тоже лучше h_vector хотя бы на ~2-4 стэковых элемента (в других where-обработчиках скорее всего тоже). Очень часто у пользователей в правой части where-условий всего по 1 значению

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/include/query_wrapper.cc
> +		return reindexer::Error(ErrorCode::errQueryExec, "WAL queries are not supported");
Вот эта проверка имеет смысл только для Select(если мы ориентируемся на логику ядра и хотим сэкономить на проверках), либо наоборот должна выполняться для всех запросов (если хотим перестраховаться). Я бы предложил первый вариант

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/include/query_wrapper.cc
> +	switch (type) {
Очень субъективный момент, но мне кажется, что отдельные методы под каждый тип запроса выглядели бы в API чуть проще и по объёму кода вышли бы таким же

2024-12-06 13:50 UTC, MadSchemas commented on pyreindexer/lib/include/query_wrapper.h
> +	std::vector<QueryWrapper*> mergedQueries_;
Тут для joined/merged напрашивается h_vector, так как их зачастую либо нет вообще, либо мало, а лежащий в векторе тип (указатель) позволяет довольно большую стэковую область ему задать (штук по 8, например). Хотя здесь это не настолько ощутимо, как для where-условий

2024-12-06 17:10 UTC, AlexAUtkin commented on .github/workflows/deploy-workflow.yml
> +          attestations: false
3 warnings
[attestations input ignored](https://github.com/Restream/reindexer-py/actions/runs/12199978260/job/34035482261#step:3:141)
The workflow was run with the 'attestations: true' input, but an explicit password was also set, disabling Trusted Publishing. As a result, the attestations input is ignored.

2024-12-06 17:11 UTC, AlexAUtkin commented on pyreindexer/query.py
> +    def op_and(self) -> Query:
зарезервированные слова в языке

2024-12-06 17:17 UTC, AlexAUtkin commented on pyreindexer/query.py
> +    def where_uuid(self, index: str, condition: CondType, *keys: str) -> Query:
Может, но я сходу не нашёл, как их в CPython передать

2024-12-09 07:43 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<reindexer::Variant> keys;
Знаешь, я бы тоже. Однако я не понимаю логики использования данного класса. Откроем, например, Query.h\Query.cc: Раз 8 есть код:
```c++
VariantArray values;
values.reserve(l.size());
for (auto it = l.begin(); it != l.end(); it++) {
    values.emplace_back(*it);
}
```
Почему нет MarkArray()?

2024-12-09 09:37 UTC, AlexAUtkin commented on pyreindexer/lib/include/query_wrapper.cc
> +	switch (type) {
Субъективно соглашусь. Здесь этого не видно, а вот в rawpyrindexer.cc, прийдётся в это случае дважды продублировать:
```c++
static PyObject* executeQuery(PyObject* self, PyObject* args, QueryWrapper::ExecuteType type) {
	uintptr_t queryWrapperAddr = 0;
	if (!PyArg_ParseTuple(args, "k", &queryWrapperAddr)) {
		return nullptr;
	}

	auto query = getWrapper<QueryWrapper>(queryWrapperAddr);

	auto qresWrapper = std::make_unique<QueryResultsWrapper>(query->GetDB());
	auto err = query->ExecuteQuery(type, *qresWrapper);
	if (!err.ok()) {
		return Py_BuildValue("iskII", err.code(), err.what().c_str(), 0, 0, 0);
	}

	auto count = qresWrapper->Count();
	auto totalCount = qresWrapper->TotalCount();
	return Py_BuildValue("iskII", err.code(), err.what().c_str(),
						 reinterpret_cast<uintptr_t>(qresWrapper.release()), count, totalCount);
}
```
ради чего это и затевалось.
Хорошо, чуть переделаю

2024-12-09 15:29 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<std::string> keys;
Все они проходят через один конвертор - вариативности быть не может. Поставил 2 на всех. Моё мнение - преждевременная оптимизация там где этого не требовалось

2024-12-09 15:35 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<reindexer::Variant> keys;
Внимательно просмотрел опять весь код. Не вижу ни одного кейса где бы выигрывали. Почти все они заканчиваются на функции:
```c++
void QueryWrapper::putKeys(const reindexer::VariantArray& keys) {
	ser_.PutVarUint(keys.size());
	for (const auto& key : keys) {
		ser_.PutVariant(key);
	}
}
```
и что там реально это будет, нет никакой разницы. Аллокация там одна, когда перекладываем из Питон параметров, а дальше const & и всё. Нет ни хранения, ни перекладывания. Заменил, просто короче в API функции смотрится

2024-12-09 15:39 UTC, AlexAUtkin commented on pyreindexer/query.py
> +    def where_uuid(self, index: str, condition: CondType, *keys: str) -> Query:
Можем, конечно, но я не нашёл перекладку в ваш кастомный UUID класс на уровне CPython. Куда вы его положили?

2024-12-10 18:19 UTC, AlexAUtkin commented on pyreindexer/query.py
> +    def where_uuid(self, index: str, condition: CondType, *keys: str) -> Query:
Добавил, но стало странней

2024-12-10 18:20 UTC, AlexAUtkin commented on pyreindexer/query.py
> +             keys: Union[simple_types, tuple[list[simple_types], ...]] = None) -> Query:
переделал

2024-12-10 18:20 UTC, AlexAUtkin commented on pyreindexer/lib/src/reindexerinterface.h
> +	Error err_{errOK};
поправил

2024-12-10 18:23 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<reindexer::Variant> keys;
поменял, стало хуже, появились рудименты:
```c++
std::vector<std::string> prets(itemPrecepts.begin(), itemPrecepts.end());
item.SetPrecepts(prets); // ToDo after migrate on v.4, do std::move
```
потому что там нет `h_vector`

2024-12-10 18:23 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<std::string> keys;
сделал

2024-12-10 18:23 UTC, AlexAUtkin commented on pyreindexer/lib/include/query_wrapper.cc
> +		return reindexer::Error(ErrorCode::errQueryExec, "WAL queries are not supported");
сделал

2024-12-10 18:24 UTC, AlexAUtkin commented on pyreindexer/lib/include/query_wrapper.cc
> +	switch (type) {
переделал

2024-12-10 18:25 UTC, AlexAUtkin commented on pyreindexer/lib/include/query_wrapper.h
> +	std::vector<QueryWrapper*> mergedQueries_;
сделал. Тут поддерживаю. Хотя чтобы это стало заметно, сколько Query нужно одновременно держать? Соточку?

2024-12-10 18:26 UTC, AlexAUtkin commented on pyreindexer/lib/src/reindexerinterface.cc
> +	return execute([this, query, &result] {
очепятка. Спасибо!

2024-12-10 18:28 UTC, AlexAUtkin commented on pyreindexer/lib/src/reindexerinterface.cc
> +	const int QRESULTS_FLAGS = kResultsJson | kResultsWithRank | kResultsWithJoined;
убрал

2024-12-10 18:28 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	err = item.Unsafe().FromJSON(wrSer.c_str(), 0, mode == ModeDelete);
изменил

2024-12-10 18:28 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	err = item.Unsafe().FromJSON(wrSer.c_str(), 0, mode == ModeDelete);
и тут тоже

2024-12-10 18:29 UTC, AlexAUtkin commented
Внимание! Мержить пока нельзя!!!

2024-12-11 12:04 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +	std::vector<reindexer::Variant> keys;
Там в случае VariantArray рассчёт на то, что в принципе не будет аллокаций, если аргументов 1 или 2 - они останутся на стеке (в отличие от создания промежуточного вектора для keys, который аллоцирует в любом случае в момент reserve()).

Но да, с перцептами оно, конечно, не очень выглядит(

2024-12-11 12:12 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		std::vector<std::string> prets(itemPrecepts.begin(), itemPrecepts.end());
А тут не должно быть с move-итератором переноса? Или h_vector в него не умеет?
```
std::vector<std::string> prets(std::make_move_iterator(itemPrecepts.begin()), std::make_move_iterator(itemPrecepts.end()));
```

2024-12-11 12:18 UTC, MadSchemas commented on pyreindexer/lib/include/query_wrapper.h
> +	std::vector<QueryWrapper*> mergedQueries_;
Тут вопрос не в том, сколько их нужно держать, а в том, как часто они выполняются и какое распределение у запросов. Если у пользователя, например, 40к RPS и каждый запрос с 1 джоином, то экономится 40к аллокаций в секунду (это вроде как заметно). Если у него джоинов нет вообще, или они все наоборо большие, то не экономится ничего

2024-12-11 12:38 UTC, MadSchemas commented on pyreindexer/query.py
> +    def where_uuid(self, index: str, condition: CondType, *keys: str) -> Query:
Перекладке UUID в reindexer::UUID в CPython просто неоткуда было взяться - в байндинге нигде не нужен был до этого тип UUID. (Ты вот её тоже не реализовал)

Конвертация через строку, конечно, сомнительная, но оно теперь по крайней мере со стороны python API чуть больше ограничений накладывает

2024-12-11 13:51 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		std::vector<std::string> prets(itemPrecepts.begin(), itemPrecepts.end());
> "бы быть шаблонным"
Я не люблю type_traits и duck-typing, а как это сделать без них я не знаю

2024-12-11 14:01 UTC, MadSchemas commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		std::vector<std::string> prets(itemPrecepts.begin(), itemPrecepts.end());
Конкретно здесь, если всё-таки добавлять шаблон, то придётся явно передавать типа возвращаемого вектора при вызове, примерно вот так:
```
using StringHVectorT = reindexer::h_vector<std::string, 2>;

template<typename VectorT = StringHVector>
VectorT ParseStrListToStrVec(...) { ... }

/// 
auto prets = ParseStrListToStrVec<std::vector<std::string>>(...);

///
auto someStrings = ParseStrListToStrVec<>(...);
```

Можно всё это ещё раз завернуть во что-то, чтобы `<>` избежать, но по факту всё равно просто сгенерятся 2 одинаковых функции под разный контейнер в итоге.

Я бы добавил, но в целом на твоё усмотрение. Более критичным тут всё же является момент с лишним копированием строк

2024-12-12 07:26 UTC, AlexAUtkin commented on pyreindexer/lib/src/rawpyreindexer.cc
> +		std::vector<std::string> prets(itemPrecepts.begin(), itemPrecepts.end());
сделано через шаблон

2024-12-12 13:03 UTC, merged